AllCops:
  Include:
    - '**/Rakefile'
  Exclude:
    - 'benchmarks/**/*'
    - 'bin/**/*'
    - 'pkg/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.2

Documentation:
  Enabled: false # TODO: Enable again once we have more docs

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 15

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'

Style/EmptyCaseCondition:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': "[]"
    '%W': "[]"
