sudo: false
language: ruby
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
services:
  - redis-server
script: bundle exec rspec
bundler_args: --without benchmarking
